(()=>{'use strict';
const input=document.querySelector('#busca'),filter=document.querySelector('#filtro'),category=document.querySelector('#categoria'),kind=document.querySelector('#tipo'),results=document.querySelector('#resultados');
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const words=s=>norm(s).split(/\s+/).filter(Boolean);
const synonyms={gq:['gq','qualificacao'],rt:['retribuicao','rt'],capacitacao:['capacitacao','capacitacoes'],pericia:['pericia','pericias'],licenca:['licenca','licencas'],ferias:['ferias'],pcctm:['pcctm','pctm'],aposentadoria:['aposentadoria','aposentadorias']};
const expanded=s=>words(s).flatMap(t=>synonyms[t]||[t]);
const data=(window.CADERNOS||[]).map(p=>({...p,normalized:norm(p.text+' '+p.title+' '+p.topic+' '+p.category+' '+p.kind)}));
function marked(el,text,query){const n=norm(text),hits=[];let cursor=0;for(const t of expanded(query)){let pos=n.indexOf(t);while(pos!==-1){hits.push([pos,pos+t.length]);pos=n.indexOf(t,pos+t.length)}}hits.sort((a,b)=>a[0]-b[0]||b[1]-a[1]);for(const [start,end] of hits){if(start<cursor)continue;el.append(document.createTextNode(text.slice(cursor,start)));const m=document.createElement('mark');m.textContent=text.slice(start,end);el.append(m);cursor=end}el.append(document.createTextNode(text.slice(cursor)))}
function matchesFilter(p){return(!filter.value||p.slug===filter.value)&&(!category.value||p.categoryId===category.value)&&(!kind.value||p.kind===kind.value)}
function catalogFilter(){let visible=0;document.querySelectorAll('.library-card').forEach(card=>{card.hidden=!matchesFilter({slug:card.dataset.slug,categoryId:card.dataset.category,kind:card.dataset.kind});if(!card.hidden)visible++});document.querySelectorAll('.category-group').forEach(group=>{group.hidden=!group.querySelector('.library-card:not([hidden])')});const empty=document.querySelector('#catalog-empty');if(empty)empty.hidden=visible>0;document.querySelectorAll('.category-nav a').forEach(a=>{const group=document.getElementById(a.hash.slice(1));a.hidden=group?.hidden||false})}
function run(){catalogFilter();const q=input.value.trim(),ts=words(q);results.replaceChildren();results.hidden=!q;if(!q)return;const matches=data.filter(p=>matchesFilter(p)&&ts.every(t=>(synonyms[t]||[t]).some(term=>p.normalized.includes(term))));const title=document.createElement('h2');title.textContent=matches.length?`${matches.length} ${matches.length===1?'página encontrada':'páginas encontradas'} para “${q}”`:`Nenhum resultado para “${q}”`;results.append(title);if(!matches.length){const p=document.createElement('p');p.textContent='Tente outra palavra ou amplie os filtros para todos os documentos.';results.append(p);return}let shown=0;const list=document.createElement('div');results.append(list);const more=document.createElement('button');more.type='button';more.textContent='Mostrar mais resultados';function add(){for(const p of matches.slice(shown,shown+30)){const a=document.createElement('a');a.className='result';a.href=`${p.slug}.html?q=${encodeURIComponent(q)}#p${p.page}`;const label=document.createElement('small');label.textContent=`${p.category} · ${p.kind} · ${p.title} · página ${p.page}`;const heading=document.createElement('h3');marked(heading,p.topic,q);const excerpt=document.createElement('p');const positions=expanded(q).map(t=>norm(p.text).indexOf(t)).filter(p=>p>=0);const start=Math.max(0,(positions.length?Math.min(...positions):0)-70);marked(excerpt,(start?'… ':'')+p.text.slice(start,start+260)+(start+260<p.text.length?' …':''),q);a.append(label,heading,excerpt);list.append(a)}shown+=30;more.hidden=shown>=matches.length}more.addEventListener('click',add);results.append(more);add()}
document.querySelector('form.search').addEventListener('submit',e=>{e.preventDefault();run();if(input.value.trim())results.scrollIntoView({block:'start'})});let timer;input.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(run,200)});[filter,category,kind].forEach(el=>el.addEventListener('change',run));document.querySelector('#limpar').addEventListener('click',()=>{input.value='';filter.value='';category.value='';kind.value='';run();input.focus();history.replaceState(null,'',location.pathname+location.hash)});
const initial=new URLSearchParams(location.search).get('q');if(initial){input.value=initial;const anchor=document.getElementById(location.hash.slice(1));if(anchor){const el=anchor.querySelector('.transcription');if(el){const txt=el.textContent;el.replaceChildren();marked(el,txt,initial)}}else run()}
})();
(()=>{const header=document.querySelector("header");const sync=()=>document.documentElement.style.setProperty("--header-height",Math.ceil(header.getBoundingClientRect().height)+"px");sync();new ResizeObserver(sync).observe(header)})();

(()=>{const toggle=document.querySelector('.menu-toggle'),menu=document.querySelector('#site-menu'),theme=document.querySelector('.theme-toggle');
function close(){menu.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir menu')}
toggle.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});
document.addEventListener('click',e=>{if(!menu.contains(e.target)&&!toggle.contains(e.target))close()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!menu.hidden){close();toggle.focus()}});menu.addEventListener('click',e=>{if(e.target.closest('a'))close()});
function label(){const dark=document.documentElement.dataset.theme==='dark';theme.querySelector('.theme-label').textContent=dark?'Claro':'Escuro';theme.setAttribute('aria-label',dark?'Ativar tema claro':'Ativar tema escuro');theme.title=theme.getAttribute('aria-label')}
theme.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('assessoria-theme',next)}catch{}label()});label();
})();
